// Generated by gencpp from file laser_line_extraction/GetGoalPose.msg
// DO NOT EDIT!


#ifndef LASER_LINE_EXTRACTION_MESSAGE_GETGOALPOSE_H
#define LASER_LINE_EXTRACTION_MESSAGE_GETGOALPOSE_H

#include <ros/service_traits.h>


#include <laser_line_extraction/GetGoalPoseRequest.h>
#include <laser_line_extraction/GetGoalPoseResponse.h>


namespace laser_line_extraction
{

struct GetGoalPose
{

typedef GetGoalPoseRequest Request;
typedef GetGoalPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetGoalPose
} // namespace laser_line_extraction


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::laser_line_extraction::GetGoalPose > {
  static const char* value()
  {
    return "9ae20343ba64ec05ab718b1738b7da43";
  }

  static const char* value(const ::laser_line_extraction::GetGoalPose&) { return value(); }
};

template<>
struct DataType< ::laser_line_extraction::GetGoalPose > {
  static const char* value()
  {
    return "laser_line_extraction/GetGoalPose";
  }

  static const char* value(const ::laser_line_extraction::GetGoalPose&) { return value(); }
};


// service_traits::MD5Sum< ::laser_line_extraction::GetGoalPoseRequest> should match
// service_traits::MD5Sum< ::laser_line_extraction::GetGoalPose >
template<>
struct MD5Sum< ::laser_line_extraction::GetGoalPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::laser_line_extraction::GetGoalPose >::value();
  }
  static const char* value(const ::laser_line_extraction::GetGoalPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::laser_line_extraction::GetGoalPoseRequest> should match
// service_traits::DataType< ::laser_line_extraction::GetGoalPose >
template<>
struct DataType< ::laser_line_extraction::GetGoalPoseRequest>
{
  static const char* value()
  {
    return DataType< ::laser_line_extraction::GetGoalPose >::value();
  }
  static const char* value(const ::laser_line_extraction::GetGoalPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::laser_line_extraction::GetGoalPoseResponse> should match
// service_traits::MD5Sum< ::laser_line_extraction::GetGoalPose >
template<>
struct MD5Sum< ::laser_line_extraction::GetGoalPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::laser_line_extraction::GetGoalPose >::value();
  }
  static const char* value(const ::laser_line_extraction::GetGoalPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::laser_line_extraction::GetGoalPoseResponse> should match
// service_traits::DataType< ::laser_line_extraction::GetGoalPose >
template<>
struct DataType< ::laser_line_extraction::GetGoalPoseResponse>
{
  static const char* value()
  {
    return DataType< ::laser_line_extraction::GetGoalPose >::value();
  }
  static const char* value(const ::laser_line_extraction::GetGoalPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LASER_LINE_EXTRACTION_MESSAGE_GETGOALPOSE_H
