// Generated by gencpp from file laser_line_extraction/GetGoalPoseRequest.msg
// DO NOT EDIT!


#ifndef LASER_LINE_EXTRACTION_MESSAGE_GETGOALPOSEREQUEST_H
#define LASER_LINE_EXTRACTION_MESSAGE_GETGOALPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace laser_line_extraction
{
template <class ContainerAllocator>
struct GetGoalPoseRequest_
{
  typedef GetGoalPoseRequest_<ContainerAllocator> Type;

  GetGoalPoseRequest_()
    {
    }
  GetGoalPoseRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::laser_line_extraction::GetGoalPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::laser_line_extraction::GetGoalPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetGoalPoseRequest_

typedef ::laser_line_extraction::GetGoalPoseRequest_<std::allocator<void> > GetGoalPoseRequest;

typedef boost::shared_ptr< ::laser_line_extraction::GetGoalPoseRequest > GetGoalPoseRequestPtr;
typedef boost::shared_ptr< ::laser_line_extraction::GetGoalPoseRequest const> GetGoalPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::laser_line_extraction::GetGoalPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::laser_line_extraction::GetGoalPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace laser_line_extraction

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::laser_line_extraction::GetGoalPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser_line_extraction::GetGoalPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::laser_line_extraction::GetGoalPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::laser_line_extraction::GetGoalPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_line_extraction::GetGoalPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_line_extraction::GetGoalPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::laser_line_extraction::GetGoalPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::laser_line_extraction::GetGoalPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::laser_line_extraction::GetGoalPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "laser_line_extraction/GetGoalPoseRequest";
  }

  static const char* value(const ::laser_line_extraction::GetGoalPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::laser_line_extraction::GetGoalPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::laser_line_extraction::GetGoalPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::laser_line_extraction::GetGoalPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetGoalPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::laser_line_extraction::GetGoalPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::laser_line_extraction::GetGoalPoseRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // LASER_LINE_EXTRACTION_MESSAGE_GETGOALPOSEREQUEST_H
