// Generated by gencpp from file laser_line_extraction/GetGoalPoseResponse.msg
// DO NOT EDIT!


#ifndef LASER_LINE_EXTRACTION_MESSAGE_GETGOALPOSERESPONSE_H
#define LASER_LINE_EXTRACTION_MESSAGE_GETGOALPOSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace laser_line_extraction
{
template <class ContainerAllocator>
struct GetGoalPoseResponse_
{
  typedef GetGoalPoseResponse_<ContainerAllocator> Type;

  GetGoalPoseResponse_()
    : pose()
    , success(false)  {
    }
  GetGoalPoseResponse_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::laser_line_extraction::GetGoalPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::laser_line_extraction::GetGoalPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetGoalPoseResponse_

typedef ::laser_line_extraction::GetGoalPoseResponse_<std::allocator<void> > GetGoalPoseResponse;

typedef boost::shared_ptr< ::laser_line_extraction::GetGoalPoseResponse > GetGoalPoseResponsePtr;
typedef boost::shared_ptr< ::laser_line_extraction::GetGoalPoseResponse const> GetGoalPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::laser_line_extraction::GetGoalPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::laser_line_extraction::GetGoalPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::laser_line_extraction::GetGoalPoseResponse_<ContainerAllocator1> & lhs, const ::laser_line_extraction::GetGoalPoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::laser_line_extraction::GetGoalPoseResponse_<ContainerAllocator1> & lhs, const ::laser_line_extraction::GetGoalPoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace laser_line_extraction

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::laser_line_extraction::GetGoalPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser_line_extraction::GetGoalPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::laser_line_extraction::GetGoalPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::laser_line_extraction::GetGoalPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_line_extraction::GetGoalPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_line_extraction::GetGoalPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::laser_line_extraction::GetGoalPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9ae20343ba64ec05ab718b1738b7da43";
  }

  static const char* value(const ::laser_line_extraction::GetGoalPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9ae20343ba64ec05ULL;
  static const uint64_t static_value2 = 0xab718b1738b7da43ULL;
};

template<class ContainerAllocator>
struct DataType< ::laser_line_extraction::GetGoalPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "laser_line_extraction/GetGoalPoseResponse";
  }

  static const char* value(const ::laser_line_extraction::GetGoalPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::laser_line_extraction::GetGoalPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped pose\n"
"bool success\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::laser_line_extraction::GetGoalPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::laser_line_extraction::GetGoalPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetGoalPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::laser_line_extraction::GetGoalPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::laser_line_extraction::GetGoalPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LASER_LINE_EXTRACTION_MESSAGE_GETGOALPOSERESPONSE_H
